

pipelines:
  branches:
    dev:
      - step:
          name: Build and Push
          script:
            - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD https://registry.com
            - docker build -t https://registry.com/app:dev_latest .
            - docker push https://registry.com/app:dev_latest
          services:
            - docker
      - step:
          name: Deploy to Dev
          deployment: Dev
          clone:
            enabled: false
          script:
            - pipe: atlassian/ssh-run:0.4.0
              variables:
                COMMAND: >
                  docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWORD} https://registry.com/app
                  && docker pull https://registry.com/app:dev_latest
                  && cd /var/www/ && docker-compose up -d
