version: "3.9"
services:
  api:
    build: .
    image: ${REGISTRY}/${API_IMAGE}:${TAG}
    container_name: myproject-api-app
    ports:
      - "8888:8000"
    volumes:
      - /var/data:/var/data
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "DB"
      POSTGRES_USER: "USER"
      POSTGRES_PASSWORD: "PASSWORD"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: pg_isready -U user -d appDB
      interval: 1s
      timeout: 2s
      retries: 5
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "54321:5432"
    networks:
      app-network:
        aliases:
          - database
networks:
  app-network:
volumes:
  postgres_data:


